### ISSUE TITLE
Support for IDENTIFY after getting 005 / ISUPPORT code

### ISSUE THREAD

**Issue by filippog** [google/alertmanager-irc-relay#14]
Hello,
I'm running alertmanager-irc-relay on libera.chat and nickserv apparently doesn't send NOTICE anymore after the first connection. The end result being the bot never identifies to nickserv; apparently it should be ok to (attempt to) IDENTIFY to nickserv after receiving `005` (aka `ISUPPORT`) from the server on first connection. The proper solution is of course SASL in #12 although this seems an easier fix/implementation

**Comment by shammash** [comment]
Thanks for flagging compatibility issues with libera.chat .

First of all, I agree that SASL support would be the proper solution, generally speaking.

I have just checked the bot with a registered nickname on libera.chat . The default list of `nickserv_identify_patterns` does not recognize the NOTICE sent by the Atheme nickserv used by libera.chat ( https://github.com/atheme/atheme/blob/master/modules/nickserv/main.c#L80 ).

I have just pushed 33fe9e4ef89b513d7b7580a168201df573511e88 to update the list and cut a new release.

If you do not want to update to the new version you can add the following to your config file:
```
nickserv_identify_patterns:
  - "Please choose a different nickname, or identify via"
```
