### ISSUE TITLE
Support for multiple lines

### ISSUE THREAD

**Issue by pinpox** [google/alertmanager-irc-relay#15]
Newlines currently seem to be broken.
When using a template with multiple lines, only the first line is printed.
```mustache
   ⚠ ⚠ ⚠ [{{.Labels.instance}}] - {{ .Labels.alertname }} is {{.Status}} ⚠ ⚠ ⚠\n{{.Annotations.description}}\n(@pinpox act accordingly)";
```
Will result in only the first line being send.

**Comment by shammash** [comment]
Good catch.

This should be fixed by https://github.com/google/alertmanager-irc-relay/commit/f7034fa2c2c93e7c5ec3c3738d836d5d095c831d . I've also cut a new release (0.4.3) for this.
