### ISSUE TITLE
IRC color codes in msg_template not accepted

### ISSUE THREAD

**Issue by lelutin** [google/alertmanager-irc-relay#22]
Hello,

I've just tried to add some IRC color codes (a litteral ctrl-c, or ascii 0x03 followed by a color number to set color text, or just the ctrl-c to clear colors) to the `msg_template` option in the alertmanager-irc-relay config file and the service refused to start.

The way I added the special characters was with vim to enter input mode, then hit ctrl-v and then ctrl-c. This outputs a litteral ctrl-c byte in the buffer.

Is there currently some other method of using IRC color codes in the message template?

**Comment by filippog** [comment]
I have had success with escape character literals in the format string, e.g. to do firing/resolved in red and green respectively: `{{ if eq .Status \"firing\" -}}\x03\x34{{- else -}}\x03\x33{{- end -}}
  {{.Status}}\x0f`

**Comment by lelutin** [comment]
@filippog thanks! I'll try that next week (and close the issue if I can confirm that it works

**Comment by lelutin** [comment]
nice, I can confirm that your template snippet works. thanks a bunch!
