### ISSUE TITLE
Unable to exit when not yet connected to IRC?

### ISSUE THREAD

**Issue by filippog** [google/alertmanager-irc-relay#6]
I'm running into a potential issue where the relay is not yet connected to irc (and backing off, using an empty/default configuration file) and upon receiving SIGTERM from systemd the daemon doesn't exit:

```
Jul 27 12:25:54 host alertmanager-irc-relay[19807]: 2020/07/27 12:25:54 Could not connect to IRC: dial tcp 93.184.216.34:7000: i/o timeout
Jul 27 12:25:54 host alertmanager-irc-relay[19807]: 2020/07/27 12:25:54 Connecting to IRC example.com:7000
Jul 27 12:25:54 host alertmanager-irc-relay[19807]: 2020/07/27 12:25:54 Backoff for 3m7s
Jul 27 12:26:00 host systemd[1]: Stopping Send Prometheus Alerts to IRC using Webhooks...
Jul 27 12:26:00 host alertmanager-irc-relay[19807]: 2020/07/27 12:26:00 Received terminated, exiting
```

Although the exit never comes and systemd eventually issues SIGKILL

```
Jul 27 12:27:30 host systemd[1]: alertmanager-irc-relay.service: State 'stop-sigterm' timed out. Killing.
Jul 27 12:27:30 host systemd[1]: alertmanager-irc-relay.service: Killing process 19807 (alertmanager-ir) with signal SIGKILL.
```

**Comment by shammash** [comment]
https://github.com/google/alertmanager-irc-relay/commit/82af7c1f6963f0d3979a9ab360bb83f4d25c9bf7 fixed part of this issue.

https://github.com/fluffle/goirc/commit/e0c319f8fff54a665d3bea2405cd51289824c3eb should fix the remaining part. Just waiting on a new goirc module release to start using ConnectContext().

**Comment by shammash** [comment]
I've opted for an unreleased version of goirc in the end: https://github.com/google/alertmanager-irc-relay/commit/a1b44d6ba9446086967b45dbba1c11fd4b7b9b30
