### ISSUE TITLE
Set password for irc server (not only for channel)

### ISSUE THREAD

**Issue by mguthmuller** [google/alertmanager-irc-relay#7]
Hello,

I'm not able to connect the bot to the irc server. This server uses SSL but also have a password before connecting to channels. I tried to put this password in irc_channels config (password field) but it does not work...

I always have these errors:

```
alertmanager-irc-relay    | 2020/09/04 07:31:21 Connecting to IRC myIRCserver:7000
alertmanager-irc-relay    | 2020/09/04 07:31:21 Starting HTTP server
alertmanager-irc-relay    | 2020/09/04 07:31:21 Backoff for 0s
alertmanager-irc-relay    | 2020/09/04 07:31:21 Connected to IRC server, waiting to establish session
alertmanager-irc-relay    | 2020/09/04 07:31:21 Disconnected from IRC
alertmanager-irc-relay    | 2020/09/04 07:31:21 Deregistering all channels
```

End when an alert is firing:

```
alertmanager-irc-relay    | 2020/09/04 07:35:14 Connected to IRC server, waiting to establish session
alertmanager-irc-relay    | 2020/09/04 07:35:14 Cannot send alert to #mychannel : IRC not connected
```

Any idea?

**Comment by shammash** [comment]
Hi,

Thank you for reporting this issue.

That's right, the bot did not handle the IRC server password.

I have just pushed commit 826f088241409dfeb72ec864d386edc324ccf649 which adds an optional config parameter 'irc_host_password' to specify the IRC server password.

I am going to close this issue. Please feel free to reopen if this is not covering your use case.

Thank you,

Luca
